### ISSUE TITLE
Update BottomFooter to use siteMetadata

### ISSUE THREAD

**Issue by murtuzasyed** [Pitayan/gatsby-theme-pitayan#24]
Hi, Thanks for the great work in creating this theme. Trying to use it for a pet project and was looking to know if we can update the BottomFooter component to use siteMetadata https://github.com/Pitayan/gatsby-theme-pitayan/blob/master/packages/gatsby-theme-pitayan/src/components/BottomFooter/index.tsx#L21

**Comment by daiyanze** [comment]
Oops. That's a mistake. I can take care of this soon

**Comment by murtuzasyed** [comment]
Awesome, Thanks @daiyanze

**Comment by daiyanze** [comment]
Hi @murtuzasyed!
I think I've fixed the issue with this PR https://github.com/Pitayan/gatsby-theme-pitayan/pull/27.

A prerelease version has been published to NPM ([0.4.3-next.0](https://www.npmjs.com/package/@pitayan/gatsby-theme-pitayan/v/0.4.3-next.0)). Could you please try it out on your side?

**Comment by murtuzasyed** [comment]
@daiyanze , thanks for the update. It works now for the name but the site description is empty. Here;s how my configuration looks 
![image](https://user-images.githubusercontent.com/34487985/190839404-c601f9bf-6fc8-4611-84a7-b142a36c4cb4.png)
![image](https://user-images.githubusercontent.com/34487985/190839410-aabe60ec-f6c4-4e6a-b55d-726515176cae.png)

**Comment by daiyanze** [comment]
@murtuzasyed Your configs look good to me (except the "description" under the plugin options. You don't need to put description there).

It worked for me just by changing the `name` and `description` of `siteMetadata`.

![image](https://user-images.githubusercontent.com/14920529/190849051-db5141a9-f25a-4326-9ed5-4a8d4e1ee50b.png)
<img width="430" alt="image" src="https://user-images.githubusercontent.com/14920529/190849059-957e7a95-6840-4936-be20-96116abc51d6.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/14920529/190849067-876a34c6-6017-4628-9602-6b6923cebc3e.png">

Maybe you could try removing the Gatsby cache?

**Comment by daiyanze** [comment]
Hi @murtuzasyed! Let me merge this PR #27 to fix the issue. Please open up a new issue ticket if the above mentioning doesn't help out.
