### ISSUE TITLE
Disable email/mailchimp "banner"

### ISSUE THREAD

**Issue by remiks** [Pitayan/gatsby-theme-pitayan#29]
Is there any way I can disable the whole banner and hide the subscription to newsletter?

<img width="896" alt="image" src="https://user-images.githubusercontent.com/14348906/206754062-b9f56751-84f4-4005-abc8-1fdf167f43d7.png">

**Comment by daiyanze** [comment]
There's not such option to directly hide the subscription panel. But there's a css class attached to such component.
You could just override the style to achieve hiding it.

Create a stylesheet file under `src/assets/`. This also supports Tailwindcss @apply.
```css
.subscription {
  display: none;
}
```

**Comment by remiks** [comment]
Awesome! Thanks @daiyanze !
