### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by daiyanze** [Pitayan/gatsby-theme-pitayan#33]
Requirements:

- Define default displayable levels (maybe better to display only heading 1?)
- Allow users to override "levels" from plugin options and markdown frontmatter
  - Use an integer property named `tableOfContentsLevels`

**Comment by daiyanze** [comment]
Design is going to be very simple. We could utilize the default set of link and list style

**Comment by remiks** [comment]
I`m thinking inspiration from MKDocs by maybe having the ToC at the right side? 
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/14348906/211144720-8941af37-c16e-4f0e-bddb-9f4707a9b627.png">

**Comment by daiyanze** [comment]
Thanks @remiks ! The current Pitayan.com already uses table of contents in the way you mentioned. I also wanted to give it a go on locating it aside of the article content. But I'm still trying if centering the article without the "table of contents" is good approach

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/14920529/211192455-f164f1a7-e415-4e59-9d2a-ffc094e5d80b.png">

**Comment by remiks** [comment]
That looks very nice! Do you have screenshots of the alternatives you're working on?

**Comment by daiyanze** [comment]
Hey @remiks , sorry about the late reply here. I did some implementation around the table of contents. Hope you enjoy the appearance and effect.

The ToC now lays to the right side of the content. I have to move the content left a bit to center of the window so that there's enough space for the ToC. It also has nice scrolling active states.

![Screen Recording 2023-01-12 at 23 48 48](https://user-images.githubusercontent.com/14920529/212101330-400b5a39-4780-4979-acf6-b707f1669ad7.gif)

**Comment by remiks** [comment]
Love it @daiyanze !! Push! :)

**Comment by daiyanze** [comment]
Another issue I got here is that this change cause some dysfunctions of the selection popup... I'll have to fix it first in order to release this ToC feature.

**Comment by daiyanze** [comment]
Have to change the layout a bit to keep the post content centered. Guess the sharing buttons is also something great to have.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/14920529/212474075-d5b636de-66b7-4220-ab19-ec7a3eccf1a5.png">

**Comment by daiyanze** [comment]
I'll run another few tests locally and release it on Sunday JST

**Comment by remiks** [comment]
Still looks nice. Not sure about the share buttons, they might look a bit weird on very wide screens? Why not keep them above or under ToC? 
<img width="306" alt="image" src="https://user-images.githubusercontent.com/14348906/212495631-312bd58e-56fb-4ac6-8761-a54738f4c220.png">

**Comment by daiyanze** [comment]
There's a max with to the post content and the ToC. So on very wide screens, I think it won't turn into weird looking.

Btw, the one you're looking at is the official blog site of Pitayan.com. I had some difficulties with Gatsby, so I made a new theme with Zola framework. I'll consider to apply some good ideas from this Zola theme to our gatsby-theme-pitayan later.
As for the ToC, it'll eventually look like the one I mentioned earlier.

**Comment by remiks** [comment]
Cool! Thanks! Looking forward to push it to our blog! :)

**Comment by remiks** [comment]
btw. I like the setup at pitayan.com really - really good!!

**Comment by daiyanze** [comment]
> btw. I like the setup at pitayan.com really - really good!!

Thanks for the comment! I'll slowly move those good parts of the zola-theme-pitayan to this plugin this year.

Btw, the new release v0.5.0 has been made. Please check it out!

Thank you so much again for the support these days. Let's keep on working for the rest features.
