### ISSUE TITLE
Failing in ci build due to missing heading tag in post markdown file

### ISSUE THREAD

**Issue by remiks** [Pitayan/gatsby-theme-pitayan#43]
Hey @daiyanze ! 
We are experiencing some trouble in building v0.5.1 in CI. Was wondering if you could have a look?
Our deploy file https://github.com/amestofortytwo/blog/blob/c4b9ba6e8840da07cbc1a331f6b090a245db84af/.github/workflows/deploy.yml 

And here`s the error action in build: https://github.com/amestofortytwo/blog/actions/runs/4143997258

**Comment by remiks** [comment]
Alright. Got it to build now! The issue was that I had two blogpost that was missing any of `H1/2/3/4/5` tag. 
Added `h1`tag and the problem was gone. Maybe you should have an error handling if there is any post that are missing it?

**Comment by daiyanze** [comment]
I see. The "table of content" didn't add default input items data which lead the type error.

**Comment by daiyanze** [comment]
Hi @remiks! I made a [beta](https://www.npmjs.com/package/@pitayan/gatsby-theme-pitayan/v/0.5.2-beta.0) release just now and hope the issue is gone.
You could also check the following page for a quick confirmation.
https://pitayan.github.io/gatsby-theme-pitayan/posts/no-heading-post/

**Comment by daiyanze** [comment]
Hello @remiks! Here's a small reminder.

FYI, I'd like to release this one soon (probably within today).
